[package]
name = "rustycheckers"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# for faster iterating times
[profile.dev]
opt-level = 1 

[dependencies]
ncurses = "5.101.0"
